server:
  port: 38080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
microservices:
  environment: dev
logging:
  level:
    io:
      github:
        elliotwils0n:
          microservices:
            user: DEBUG
