server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    eviction-interval-timer-in-ms: 5000
    enableSelfPreservation: false
